### PR TITLE
✨ [open-zaak/open-zaak#1649] Command to document envvars

### PR DESCRIPTION
**Pull request by stevenbal**
Closes https://github.com/open-zaak/open-zaak/issues/1649 partly

TODO:
- [x] add tests
- [ ] add separate flag to mark as required vs required in docker?
- [ ] move intro text to library, only override in Objects?

### CODE REVIEW

**Comment by stevenbal** [comment]
@annashamray let me know if this approach is something that you think is worthwhile, I think it could save us a lot of hassle when it comes to documenting envvars (especially those that are used by every project). Here is an example of what it looks like after running the command: https://github.com/maykinmedia/objecttypes-api/blob/66a942d613776cb1766d3da025ce5e321103cf40/docs/env_config.rst

**Comment by annashamray** [comment]
I quite like it! It also forces you to write what the env variable actually does, which is a good thing for me. 
Do you think that generating docks for djang-setup-configuration would be redundant in this case?

**Comment by stevenbal** [comment]
> Do you think that generating docks for djang-setup-configuration would be redundant in this case?

I wasn't sure, since there already were docs for those I excluded them, also because they maybe require a bit more explanation to describe the `ConfigurationStep`s as a whole

**Comment by stevenbal** [comment]
@annashamray this PR is now ready for review :)

**Review by annashamray — CHANGES_REQUESTED** [review]
Looks good! 

It would be nice to have tests for the command (and perhaps config util but it's optional)
`testapp/settings.py` seems like a perfect place to add a couple of settings with env vars

**Pull request merged**
